version: 2
jobs:
  build:
    docker:
      - image: node:latest
    working_directory: /package
    steps:
      - checkout
      - run:
          name: dependencies
          command: yarn 
      - run:
          name: test
          command: yarn test
      - run:
          name: compile
          command: yarn build
      - deploy:
          name: publish package
          command: bash ./ci/publish.sh
